openapi: 3.0.0
info:
  description: "Example REST API"
  title: "The Movies API"
  version: "0.1.0"
servers:
- url: "https://api.example.com"
paths:
  /movies:
    post:
      operationId: "addMovie"
      requestBody: 
          description: "Movie to be added"
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Movie"
      responses:
        201:
          description: "movie created"
        422:
          description: "Problems with your request"
    get:
      operationId: "listMovies"
      responses:
        200:
          description: "The list of movies"
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Movies"
            application/json:
              schema:
                $ref: "#/components/schemas/Movies"
  /directors:
    post:
      operationId: "addDirector"
      requestBody: 
          description: "Director to be added"
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Director"
      responses:
        201:
          description: "director created"
        422:
          description: "Problems with your request"
    get:
      operationId: "listDirectors"
      responses:
        200:
          description: "The list of directors"
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Directors"
            application/json:
              schema:
                $ref: "#/components/schemas/Directors"
  /actors:
    post:
      operationId: "addActor"
      requestBody: 
          description: "Actor to be added"
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Actor"
      responses:
        201:
          description: "actor created"
        422:
          description: "Problems with your request"
    get:
      operationId: "listActors"
      responses:
        200:
          description: "The list of actors"
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Actors"
            application/json:
              schema:
                $ref: "#/components/schemas/Actors"
  
  /movies/{id}:
    get:
      operationId: "getMovie"
      parameters: 
      - name: "id"
        in: path
        required: true
        description: "id of the movie"
        schema:
          type: string
      responses:
        200:
          description: "the movie"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Movie"
    delete:
      description: "deletes a single movie based on the ID supplied"
      operationId: "deleteMovie"
      parameters:
        - name: "id"
          in: path
          description: "ID of movie to delete"
          required: true
          schema:
            type: string
      responses:
        '204':
          description: "movie deleted"
  
  /movies/{movieId}/critics:
    post:
      operationId: "addCritic"
      parameters: 
      - name: "movieId"
        in: path
        required: true
        description: "id of the movie"
        schema:
          type: string
      requestBody: 
          description: "Critic to be added"
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Critic"
      responses:
        200:
          description: "List of critics from the movie"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Critics"
    get:
      operationId: "listCriticsFromMovie"
      parameters: 
      - name: "movieId"
        in: path
        required: true
        description: "id of the movie"
        schema:
          type: string
      responses:
        200:
          description: "list of critics from the movie"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Critics"
      
  /movies/{movieId}/critics/criticId}:
    
    get:
      operationId: "getCriticFromMovie"
      parameters: 
      - name: "movieId"
        in: path
        required: true
        description: "id of the movie"
        schema:
          type: string
      - name: "criticId"
        in: path
        required: true
        description: "id of the critic"
        schema:
          type: string
      responses:
        200:
          description: "Critic of the movie"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Critic"
    delete:
      description: "deletes a single critic based on the IDs supplied"
      operationId: "deleteCritic"
      parameters:
      - name: "movieId"
        in: path
        required: true
        description: "id of the movie"
        schema:
          type: string
      - name: "criticId"
        in: path
        required: true
        description: "id of the critic"
        schema:
          type: string
      
      responses:
        '204':
          description: "critic deleted"
components:
  schemas:
    Movie:
      type: "object"
      required: 
        - title
        - pitch
        - poster
        - trailer
        - actors
      properties:
        title:
          type: "string"
        pitch:
          type: "string"
        poster:
          type: "string"
        trailer:
          type: "string"
        director:
          type: "array"
          items:
            $ref: "#/components/schemas/Directors"
        actors:
          type: "array"
          items:
            $ref: "#/components/schemas/Actors"
        critics:
          type: "array"
          items:
            $ref: '#/components/schemas/Critics'
        rate:
          type: "array"
          items:
            $ref: '#/components/schemas/Rates'
    Movies:
      type: "array"
      items:
        $ref: "#/components/schemas/Movie"
    Director:
      type: "object"
      required: 
        - name
        - photo
        - country
        - bio
        - birthday
        - movies
      properties:
        name:
          type: "string"
        photo:
          type: "string"
        country:
          type: "string"
        bio:
          type: "string"
        birthday:
          type: "string"
          format: "date"
        movies:
          type: "array"
          items:
            $ref: "#/components/schemas/Movies"
    Directors:
      type: "array"
      items:
        $ref: "#/components/schemas/Director"
    Actor:
      type: "object"
      required: 
        - name
        - photo
        - country
        - bio
        - birthday
        - movies
      properties:
        name:
          type: "string"
        photo:
          type: "string"
        country:
          type: "string"
        bio:
          type: "string"
        birthday:
          type: "string"
          format: "date"
        movies:
          type: "array"
          items:
            $ref: "#/components/schemas/Movies"
    Actors:
      type: "array"
      items:
        $ref: "#/components/schemas/Actor"
    Critic:
      type: "object"
      required: 
        - content
        - movie
      properties:
        content:
          type: "string"
        movie: 
          type: "array"
          items:
            $ref: "#/components/schemas/Movie"
    Critics:
      type: "array"
      items:
        $ref: "#/components/schemas/Critic"
    Rate:
      type: "object"
      required: 
        - value
        - movie
      properties:
        value:
          type: "integer"
        movie: 
          type: "array"
          items:
            $ref: "#/components/schemas/Movie"
    Rates:
      type: "array"
      items:
        $ref: "#/components/schemas/Rate"
        
      


          
